name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  Ai_based_review_and_custom_tests_and_deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code 
        uses: actions/checkout@v3
      - name: Gen_Ai_test
        uses: actions/checkout@v4
        with:
          api_key: ${{secrets.AI_API_KEY}}
      - name: confirm ai test injestion
        run : echo "sucessfully complete AI testing"
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_KEY }}

      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test


      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.acess_key }}
          aws_secret_key: ${{ secrets.secrete_key }}
          application_name: Frontend 
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-767397800271

          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
  notify_on_failure:
    needs: Ai_based_review_and_custom_tests_and_deploy
    if: failure() && needs.Ai_based_review_and_custom_tests_and_deploy.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: sending_failure_mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smpt.gmail.com 
          server_port: 465
          username: ${{secrets.mail_username}}
          password: ${{secrets.mail_password}}
          subject: Frontend deployment failed:${{github.repository}}
          to: ${{github.event.pusher.mail}}
          from: github Actions Notifier <${{secrets.Mail_username}}>
          body: |
            the cI/CD pipeline failed for the push to **${{github.ref_name}}** by **{{github.event.pusher.name}}**.
            **workflow Run** ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
            please check the pipeline job logs details.

            Commit ID: ${{github.sha}} 

          

